spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    social:
        facebook:
            appId: 484075218448106
            appSecret: 672471632bc0bf4d07b0dd853954c3eb
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:file:./spring-blog
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone : Asia/Seoul
#        deserialization:
#            unwrap-root-value: true
#        serialization:
#            wrap-root-value: true

logging:
    level:
        com.millky.blog: DEBUG

server:
    error:
        whitelabel:
            enabled: false